//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseAllocationSystemClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/CourseAllocationSystem")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SemesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Semester {
            get {
                return this.SemesterField;
            }
            set {
                if ((this.SemesterField.Equals(value) != true)) {
                    this.SemesterField = value;
                    this.RaisePropertyChanged("Semester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectIdField, value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllocatedCourses", Namespace="http://schemas.datacontract.org/2004/07/CourseAllocationSystem")]
    [System.SerializableAttribute()]
    public partial class AllocatedCourses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Faculty1NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Faculty2NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty1Name {
            get {
                return this.Faculty1NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Faculty1NameField, value) != true)) {
                    this.Faculty1NameField = value;
                    this.RaisePropertyChanged("Faculty1Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty2Name {
            get {
                return this.Faculty2NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Faculty2NameField, value) != true)) {
                    this.Faculty2NameField = value;
                    this.RaisePropertyChanged("Faculty2Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyChoice", Namespace="http://schemas.datacontract.org/2004/07/CourseAllocationSystem")]
    [System.SerializableAttribute()]
    public partial class FacultyChoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Priority1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Priority2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Priority3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Priority4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Priority5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority1 {
            get {
                return this.Priority1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Priority1Field, value) != true)) {
                    this.Priority1Field = value;
                    this.RaisePropertyChanged("Priority1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority2 {
            get {
                return this.Priority2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Priority2Field, value) != true)) {
                    this.Priority2Field = value;
                    this.RaisePropertyChanged("Priority2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority3 {
            get {
                return this.Priority3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Priority3Field, value) != true)) {
                    this.Priority3Field = value;
                    this.RaisePropertyChanged("Priority3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority4 {
            get {
                return this.Priority4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Priority4Field, value) != true)) {
                    this.Priority4Field = value;
                    this.RaisePropertyChanged("Priority4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority5 {
            get {
                return this.Priority5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Priority5Field, value) != true)) {
                    this.Priority5Field = value;
                    this.RaisePropertyChanged("Priority5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseAllocation", Namespace="http://schemas.datacontract.org/2004/07/CourseAllocationSystem")]
    [System.SerializableAttribute()]
    public partial class CourseAllocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject1 {
            get {
                return this.Subject1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject1Field, value) != true)) {
                    this.Subject1Field = value;
                    this.RaisePropertyChanged("Subject1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject2 {
            get {
                return this.Subject2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Subject2Field, value) != true)) {
                    this.Subject2Field = value;
                    this.RaisePropertyChanged("Subject2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Faculty", Namespace="http://schemas.datacontract.org/2004/07/CourseAllocationSystem")]
    [System.SerializableAttribute()]
    public partial class Faculty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addSubject", ReplyAction="http://tempuri.org/IService1/addSubjectResponse")]
        string addSubject(CourseAllocationSystemClient.ServiceReference1.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addSubject", ReplyAction="http://tempuri.org/IService1/addSubjectResponse")]
        System.Threading.Tasks.Task<string> addSubjectAsync(CourseAllocationSystemClient.ServiceReference1.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editSubject", ReplyAction="http://tempuri.org/IService1/editSubjectResponse")]
        string editSubject(CourseAllocationSystemClient.ServiceReference1.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editSubject", ReplyAction="http://tempuri.org/IService1/editSubjectResponse")]
        System.Threading.Tasks.Task<string> editSubjectAsync(CourseAllocationSystemClient.ServiceReference1.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteSubject", ReplyAction="http://tempuri.org/IService1/deleteSubjectResponse")]
        string deleteSubject(string subjectid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteSubject", ReplyAction="http://tempuri.org/IService1/deleteSubjectResponse")]
        System.Threading.Tasks.Task<string> deleteSubjectAsync(string subjectid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNameOnUsername", ReplyAction="http://tempuri.org/IService1/getNameOnUsernameResponse")]
        string getNameOnUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNameOnUsername", ReplyAction="http://tempuri.org/IService1/getNameOnUsernameResponse")]
        System.Threading.Tasks.Task<string> getNameOnUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeFacultyChoice", ReplyAction="http://tempuri.org/IService1/storeFacultyChoiceResponse")]
        string storeFacultyChoice(string name, string priority1, string priority2, string priority3, string priority4, string priority5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeFacultyChoice", ReplyAction="http://tempuri.org/IService1/storeFacultyChoiceResponse")]
        System.Threading.Tasks.Task<string> storeFacultyChoiceAsync(string name, string priority1, string priority2, string priority3, string priority4, string priority5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeCourseAllocation", ReplyAction="http://tempuri.org/IService1/storeCourseAllocationResponse")]
        string storeCourseAllocation(CourseAllocationSystemClient.ServiceReference1.AllocatedCourses course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/storeCourseAllocation", ReplyAction="http://tempuri.org/IService1/storeCourseAllocationResponse")]
        System.Threading.Tasks.Task<string> storeCourseAllocationAsync(CourseAllocationSystemClient.ServiceReference1.AllocatedCourses course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllSubjects", ReplyAction="http://tempuri.org/IService1/getAllSubjectsResponse")]
        string[] getAllSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllSubjects", ReplyAction="http://tempuri.org/IService1/getAllSubjectsResponse")]
        System.Threading.Tasks.Task<string[]> getAllSubjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjects", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjects", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjectsSix", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsSixResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjectsSix();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjectsSix", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsSixResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsSixAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjectsFour", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsFourResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjectsFour();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEvenSubjectsFour", ReplyAction="http://tempuri.org/IService1/getEvenSubjectsFourResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsFourAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjects", ReplyAction="http://tempuri.org/IService1/getOddSubjectsResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjects", ReplyAction="http://tempuri.org/IService1/getOddSubjectsResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjectsThree", ReplyAction="http://tempuri.org/IService1/getOddSubjectsThreeResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjectsThree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjectsThree", ReplyAction="http://tempuri.org/IService1/getOddSubjectsThreeResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsThreeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjectsFive", ReplyAction="http://tempuri.org/IService1/getOddSubjectsFiveResponse")]
        CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjectsFive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOddSubjectsFive", ReplyAction="http://tempuri.org/IService1/getOddSubjectsFiveResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsFiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacultyChoices", ReplyAction="http://tempuri.org/IService1/GetFacultyChoicesResponse")]
        CourseAllocationSystemClient.ServiceReference1.FacultyChoice[] GetFacultyChoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacultyChoices", ReplyAction="http://tempuri.org/IService1/GetFacultyChoicesResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.FacultyChoice[]> GetFacultyChoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacultyNames", ReplyAction="http://tempuri.org/IService1/GetFacultyNamesResponse")]
        string[] GetFacultyNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacultyNames", ReplyAction="http://tempuri.org/IService1/GetFacultyNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetFacultyNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addAllocation", ReplyAction="http://tempuri.org/IService1/addAllocationResponse")]
        int addAllocation(CourseAllocationSystemClient.ServiceReference1.CourseAllocation courseAllocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addAllocation", ReplyAction="http://tempuri.org/IService1/addAllocationResponse")]
        System.Threading.Tasks.Task<int> addAllocationAsync(CourseAllocationSystemClient.ServiceReference1.CourseAllocation courseAllocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/courseAllocations", ReplyAction="http://tempuri.org/IService1/courseAllocationsResponse")]
        CourseAllocationSystemClient.ServiceReference1.CourseAllocation[] courseAllocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/courseAllocations", ReplyAction="http://tempuri.org/IService1/courseAllocationsResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.CourseAllocation[]> courseAllocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addFaculty", ReplyAction="http://tempuri.org/IService1/addFacultyResponse")]
        CourseAllocationSystemClient.ServiceReference1.Faculty addFaculty(CourseAllocationSystemClient.ServiceReference1.Faculty faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addFaculty", ReplyAction="http://tempuri.org/IService1/addFacultyResponse")]
        System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Faculty> addFacultyAsync(CourseAllocationSystemClient.ServiceReference1.Faculty faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFaculty", ReplyAction="http://tempuri.org/IService1/deleteFacultyResponse")]
        int deleteFaculty(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFaculty", ReplyAction="http://tempuri.org/IService1/deleteFacultyResponse")]
        System.Threading.Tasks.Task<int> deleteFacultyAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/facultyCount", ReplyAction="http://tempuri.org/IService1/facultyCountResponse")]
        int facultyCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/facultyCount", ReplyAction="http://tempuri.org/IService1/facultyCountResponse")]
        System.Threading.Tasks.Task<int> facultyCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/choiceCount", ReplyAction="http://tempuri.org/IService1/choiceCountResponse")]
        int choiceCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/choiceCount", ReplyAction="http://tempuri.org/IService1/choiceCountResponse")]
        System.Threading.Tasks.Task<int> choiceCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteChoices", ReplyAction="http://tempuri.org/IService1/deleteChoicesResponse")]
        int deleteChoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteChoices", ReplyAction="http://tempuri.org/IService1/deleteChoicesResponse")]
        System.Threading.Tasks.Task<int> deleteChoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteAllocation", ReplyAction="http://tempuri.org/IService1/deleteAllocationResponse")]
        int deleteAllocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteAllocation", ReplyAction="http://tempuri.org/IService1/deleteAllocationResponse")]
        System.Threading.Tasks.Task<int> deleteAllocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSemestertype", ReplyAction="http://tempuri.org/IService1/AddSemestertypeResponse")]
        string AddSemestertype(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSemestertype", ReplyAction="http://tempuri.org/IService1/AddSemestertypeResponse")]
        System.Threading.Tasks.Task<string> AddSemestertypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSemesterType", ReplyAction="http://tempuri.org/IService1/GetSemesterTypeResponse")]
        string GetSemesterType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSemesterType", ReplyAction="http://tempuri.org/IService1/GetSemesterTypeResponse")]
        System.Threading.Tasks.Task<string> GetSemesterTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSemesterType", ReplyAction="http://tempuri.org/IService1/DeleteSemesterTypeResponse")]
        void DeleteSemesterType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSemesterType", ReplyAction="http://tempuri.org/IService1/DeleteSemesterTypeResponse")]
        System.Threading.Tasks.Task DeleteSemesterTypeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CourseAllocationSystemClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CourseAllocationSystemClient.ServiceReference1.IService1>, CourseAllocationSystemClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string addSubject(CourseAllocationSystemClient.ServiceReference1.Subject subject) {
            return base.Channel.addSubject(subject);
        }
        
        public System.Threading.Tasks.Task<string> addSubjectAsync(CourseAllocationSystemClient.ServiceReference1.Subject subject) {
            return base.Channel.addSubjectAsync(subject);
        }
        
        public string editSubject(CourseAllocationSystemClient.ServiceReference1.Subject subject) {
            return base.Channel.editSubject(subject);
        }
        
        public System.Threading.Tasks.Task<string> editSubjectAsync(CourseAllocationSystemClient.ServiceReference1.Subject subject) {
            return base.Channel.editSubjectAsync(subject);
        }
        
        public string deleteSubject(string subjectid) {
            return base.Channel.deleteSubject(subjectid);
        }
        
        public System.Threading.Tasks.Task<string> deleteSubjectAsync(string subjectid) {
            return base.Channel.deleteSubjectAsync(subjectid);
        }
        
        public string getNameOnUsername(string username) {
            return base.Channel.getNameOnUsername(username);
        }
        
        public System.Threading.Tasks.Task<string> getNameOnUsernameAsync(string username) {
            return base.Channel.getNameOnUsernameAsync(username);
        }
        
        public string storeFacultyChoice(string name, string priority1, string priority2, string priority3, string priority4, string priority5) {
            return base.Channel.storeFacultyChoice(name, priority1, priority2, priority3, priority4, priority5);
        }
        
        public System.Threading.Tasks.Task<string> storeFacultyChoiceAsync(string name, string priority1, string priority2, string priority3, string priority4, string priority5) {
            return base.Channel.storeFacultyChoiceAsync(name, priority1, priority2, priority3, priority4, priority5);
        }
        
        public string storeCourseAllocation(CourseAllocationSystemClient.ServiceReference1.AllocatedCourses course) {
            return base.Channel.storeCourseAllocation(course);
        }
        
        public System.Threading.Tasks.Task<string> storeCourseAllocationAsync(CourseAllocationSystemClient.ServiceReference1.AllocatedCourses course) {
            return base.Channel.storeCourseAllocationAsync(course);
        }
        
        public string[] getAllSubjects() {
            return base.Channel.getAllSubjects();
        }
        
        public System.Threading.Tasks.Task<string[]> getAllSubjectsAsync() {
            return base.Channel.getAllSubjectsAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjects() {
            return base.Channel.getEvenSubjects();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsAsync() {
            return base.Channel.getEvenSubjectsAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjectsSix() {
            return base.Channel.getEvenSubjectsSix();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsSixAsync() {
            return base.Channel.getEvenSubjectsSixAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getEvenSubjectsFour() {
            return base.Channel.getEvenSubjectsFour();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getEvenSubjectsFourAsync() {
            return base.Channel.getEvenSubjectsFourAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjects() {
            return base.Channel.getOddSubjects();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsAsync() {
            return base.Channel.getOddSubjectsAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjectsThree() {
            return base.Channel.getOddSubjectsThree();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsThreeAsync() {
            return base.Channel.getOddSubjectsThreeAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Subject[] getOddSubjectsFive() {
            return base.Channel.getOddSubjectsFive();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Subject[]> getOddSubjectsFiveAsync() {
            return base.Channel.getOddSubjectsFiveAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.FacultyChoice[] GetFacultyChoices() {
            return base.Channel.GetFacultyChoices();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.FacultyChoice[]> GetFacultyChoicesAsync() {
            return base.Channel.GetFacultyChoicesAsync();
        }
        
        public string[] GetFacultyNames() {
            return base.Channel.GetFacultyNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFacultyNamesAsync() {
            return base.Channel.GetFacultyNamesAsync();
        }
        
        public int addAllocation(CourseAllocationSystemClient.ServiceReference1.CourseAllocation courseAllocation) {
            return base.Channel.addAllocation(courseAllocation);
        }
        
        public System.Threading.Tasks.Task<int> addAllocationAsync(CourseAllocationSystemClient.ServiceReference1.CourseAllocation courseAllocation) {
            return base.Channel.addAllocationAsync(courseAllocation);
        }
        
        public CourseAllocationSystemClient.ServiceReference1.CourseAllocation[] courseAllocations() {
            return base.Channel.courseAllocations();
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.CourseAllocation[]> courseAllocationsAsync() {
            return base.Channel.courseAllocationsAsync();
        }
        
        public CourseAllocationSystemClient.ServiceReference1.Faculty addFaculty(CourseAllocationSystemClient.ServiceReference1.Faculty faculty) {
            return base.Channel.addFaculty(faculty);
        }
        
        public System.Threading.Tasks.Task<CourseAllocationSystemClient.ServiceReference1.Faculty> addFacultyAsync(CourseAllocationSystemClient.ServiceReference1.Faculty faculty) {
            return base.Channel.addFacultyAsync(faculty);
        }
        
        public int deleteFaculty(string name) {
            return base.Channel.deleteFaculty(name);
        }
        
        public System.Threading.Tasks.Task<int> deleteFacultyAsync(string name) {
            return base.Channel.deleteFacultyAsync(name);
        }
        
        public int facultyCount() {
            return base.Channel.facultyCount();
        }
        
        public System.Threading.Tasks.Task<int> facultyCountAsync() {
            return base.Channel.facultyCountAsync();
        }
        
        public int choiceCount() {
            return base.Channel.choiceCount();
        }
        
        public System.Threading.Tasks.Task<int> choiceCountAsync() {
            return base.Channel.choiceCountAsync();
        }
        
        public int deleteChoices() {
            return base.Channel.deleteChoices();
        }
        
        public System.Threading.Tasks.Task<int> deleteChoicesAsync() {
            return base.Channel.deleteChoicesAsync();
        }
        
        public int deleteAllocation() {
            return base.Channel.deleteAllocation();
        }
        
        public System.Threading.Tasks.Task<int> deleteAllocationAsync() {
            return base.Channel.deleteAllocationAsync();
        }
        
        public string AddSemestertype(string type) {
            return base.Channel.AddSemestertype(type);
        }
        
        public System.Threading.Tasks.Task<string> AddSemestertypeAsync(string type) {
            return base.Channel.AddSemestertypeAsync(type);
        }
        
        public string GetSemesterType() {
            return base.Channel.GetSemesterType();
        }
        
        public System.Threading.Tasks.Task<string> GetSemesterTypeAsync() {
            return base.Channel.GetSemesterTypeAsync();
        }
        
        public void DeleteSemesterType() {
            base.Channel.DeleteSemesterType();
        }
        
        public System.Threading.Tasks.Task DeleteSemesterTypeAsync() {
            return base.Channel.DeleteSemesterTypeAsync();
        }
    }
}
